services:
  postgres:
    image: postgres:16
    container_name: messageboard-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messageboard
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
